import { PetMemory, MischiefItem, SpontaneousEvent, UserPetPersonality } from './types';

export const INITIAL_MEMORIES: PetMemory[] = [
  // --- INICIALES / HITOS ---
  {
    id: 'mem-first-day',
    title: 'Primer día juntos',
    description: 'El comienzo de una amistad para toda la vida. Golden llegó a casa moviendo la cola.',
    icon: '🐶',
    category: 'milestone',
    unlocked: true, // Unlocked at onboarding / start
    unlockedAt: new Date().toLocaleDateString('es-ES', { day: 'numeric', month: 'short', year: 'numeric' }),
    levelRecorded: 1,
    dayRecorded: 1,
    rewardXp: 30,
    rewardCoins: 50,
    rewardBones: 1,
    secret: false,
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Golden exploró cada rincón oliéndolo todo y decidió que su lugar favorito es a tu lado.',
  },
  {
    id: 'mem-first-pet',
    title: 'Primera caricia',
    description: 'Golden sintió tu cariño por primera vez y se dio la vuelta mostrando su pancita.',
    icon: '❤️',
    category: 'milestone',
    unlocked: false,
    rewardXp: 40,
    rewardCoins: 25,
    rewardBones: 1,
    secret: false,
    hint: 'Acaricia a Golden tocándolo en la pantalla.',
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Sus ojos brillaron y empezó a mover su patita al compás del masaje en la panza.',
  },
  {
    id: 'mem-first-meal',
    title: 'Primera comida',
    description: 'Un plato lleno de sabor y una cola moviéndose como hélice de helicóptero.',
    icon: '🍖',
    category: 'milestone',
    unlocked: false,
    rewardXp: 35,
    rewardCoins: 30,
    rewardBones: 1,
    secret: false,
    hint: 'Aliméntalo con croquetas o su premio favorito.',
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=600&q=80',
    eventStory: 'En menos de diez segundos el plato quedó impecable, ¡hasta relamido!',
  },
  {
    id: 'mem-first-play',
    title: 'Primer juego',
    description: 'Lanzaste la pelota y Golden corrió como un rayo dorado para traértela.',
    icon: '⚽',
    category: 'milestone',
    unlocked: false,
    rewardXp: 45,
    rewardCoins: 35,
    rewardBones: 1,
    secret: false,
    hint: 'Lanza la pelota de tenis o juega un minijuego con él.',
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Regresó orgulloso con la pelota llena de baba y esperando el próximo lanzamiento.',
  },
  {
    id: 'mem-first-bath',
    title: 'Primer baño',
    description: 'Entre burbujas de champú y salpicones de agua tibia, Golden quedó reluciente.',
    icon: '🛁',
    category: 'milestone',
    unlocked: false,
    rewardXp: 50,
    rewardCoins: 40,
    rewardBones: 1,
    rewardAccessoryId: 'bandana-fresh',
    secret: false,
    hint: 'Completa un baño con agua, champú, enjuague y secado.',
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=600&q=80',
    eventStory: 'El agua salpicó todo el cuarto, pero terminó oliendo a galletitas y con pelaje de algodón.',
  },
  {
    id: 'mem-first-nap',
    title: 'Primera siesta',
    description: 'Bostezó hondo, dio tres vueltas sobre su cojín y se durmió plácidamente.',
    icon: '😴',
    category: 'milestone',
    unlocked: false,
    rewardXp: 40,
    rewardCoins: 30,
    rewardBones: 1,
    secret: false,
    hint: 'Pon a descansar a Golden cuando tenga sueño.',
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Se le movían los bigotes mientras soñaba que corría por un campo de salchichas.',
  },
  {
    id: 'mem-sock-stolen',
    title: 'Primer calcetín robado',
    description: 'Golden descubrió que los calcetines son mucho más divertidos cuando no son suyos.',
    icon: '🧦',
    category: 'mischief',
    unlocked: false,
    rewardXp: 50,
    rewardCoins: 40,
    rewardBones: 2,
    secret: false,
    hint: 'Atrapa a Golden cuando se escape con un calcetín.',
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Huyó a toda velocidad con la punta del calcetín colgando y cara de victoria absoluta.',
  },
  {
    id: 'mem-slipper-stolen',
    title: 'Primera chancleta',
    description: 'La chancleta de andar por casa se convirtió en el trofeo más preciado de la sala.',
    icon: '🩴',
    category: 'mischief',
    unlocked: false,
    rewardXp: 50,
    rewardCoins: 35,
    rewardBones: 1,
    secret: false,
    hint: 'Recupera la chancleta cuando Golden la tome.',
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=600&q=80',
    eventStory: 'La dejó suavemente en tus pies después de presumirla por toda la casa.',
  },
  {
    id: 'mem-food-stolen',
    title: 'Primer robo de comida',
    description: 'Una mirada inocente, un paso sigiloso... y ¡adiós a ese bocado de la mesa!',
    icon: '🍗',
    category: 'mischief',
    unlocked: false,
    rewardXp: 55,
    rewardCoins: 45,
    rewardBones: 2,
    secret: false,
    hint: 'Vive el evento del robo de comida en las travesuras.',
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Puso su mejor cara de "yo no fui, el sándwich se cayó solo en mi boca".',
  },
  {
    id: 'mem-first-mischief',
    title: 'Primera travesura',
    description: 'Oficialmente Golden ha inaugurado su carrera como adorable pequeño travieso.',
    icon: '😂',
    category: 'mischief',
    unlocked: false,
    rewardXp: 45,
    rewardCoins: 30,
    rewardBones: 1,
    secret: false,
    hint: 'Resuelve cualquier travesura con Golden.',
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1591769225440-811ad7d6eab2?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Imposible enfadarse cuando te mira inclinando la cabeza con esos ojitos brillantes.',
  },
  {
    id: 'mem-first-surprise',
    title: 'Primer evento sorpresa',
    description: 'Lo inesperado ocurrió: Golden protagonizó un momento espontáneo y mágico.',
    icon: '🎉',
    category: 'routine',
    unlocked: false,
    rewardXp: 50,
    rewardCoins: 40,
    rewardBones: 1,
    secret: false,
    hint: 'Participa en un evento espontáneo mientras juegas.',
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Un día cualquiera se convirtió en una anécdota inolvidable.',
  },
  {
    id: 'mem-lvl-10',
    title: 'Cachorro Grande: Nivel 10',
    description: 'Golden ya no es tan novato; ha aprendido trucos y desarrollado gran confianza.',
    icon: '🏆',
    category: 'milestone',
    unlocked: false,
    rewardXp: 100,
    rewardCoins: 150,
    rewardBones: 3,
    secret: false,
    hint: 'Alcanza el nivel 10 cuidando y jugando a diario.',
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Su pelaje se ve más brillante y su vínculo contigo es indestructible.',
  },
  {
    id: 'mem-lvl-25',
    title: 'Maestro Peludo: Nivel 25',
    description: 'Un cuarto de camino a la leyenda perruna. Conoce cada tono de tu voz.',
    icon: '👑',
    category: 'milestone',
    unlocked: false,
    rewardXp: 250,
    rewardCoins: 300,
    rewardBones: 5,
    secret: false,
    hint: 'Alcanza el nivel 25.',
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Los vecinos dicen que es el perro más feliz y consentido del vecindario.',
  },
  {
    id: 'mem-lvl-50',
    title: 'Leyenda Dorada: Nivel 50',
    description: 'El estatus máximo de complicidad y lealtad entre un humano y su Golden.',
    icon: '🌟',
    category: 'milestone',
    unlocked: false,
    rewardXp: 500,
    rewardCoins: 800,
    rewardBones: 10,
    secret: false,
    hint: 'Alcanza el nivel 50.',
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1534361960057-19889db9621e?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Una historia grabada para siempre en el corazón de ambos.',
  },

  // --- RECUERDOS SECRETOS ---
  {
    id: 'mem-sec-escape',
    title: 'El gran escape',
    description: 'Logró zafarse sigilosamente hacia el patio para perseguir a una mariposa imaginaria.',
    icon: '🦋',
    category: 'secret',
    unlocked: false,
    secret: true,
    hint: 'Este recuerdo todavía no ha sido descubierto.',
    rewardXp: 60,
    rewardCoins: 50,
    rewardBones: 2,
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Saltó con las cuatro patas juntas intentando atrapar el rayo de sol que entraba por la ventana.',
  },
  {
    id: 'mem-sec-who-left-that',
    title: '¿Quién dejó eso ahí?',
    description: 'Descubrió un objeto misterioso detrás del sofá y lo trajo orgulloso a tus manos.',
    icon: '🕵️',
    category: 'secret',
    unlocked: false,
    secret: true,
    hint: 'Este recuerdo todavía no ha sido descubierto.',
    rewardXp: 55,
    rewardCoins: 45,
    rewardBones: 1,
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1583511655826-05700d52f4d9?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Caminaba como un detective profesional pisando puntitas para no alertar a nadie.',
  },
  {
    id: 'mem-sec-food-thief',
    title: 'El ladrón de comida',
    description: 'Consiguió un bocado prohibido con una velocidad que desafió las leyes de la física.',
    icon: '🍕',
    category: 'secret',
    unlocked: false,
    secret: true,
    hint: 'Este recuerdo todavía no ha sido descubierto.',
    rewardXp: 65,
    rewardCoins: 55,
    rewardBones: 2,
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Ni los satélites más avanzados detectaron el movimiento de su hocico.',
  },
  {
    id: 'mem-sec-bath-disaster',
    title: 'El desastre del baño',
    description: 'Un sacudón épico después de lavarse que convirtió el baño en un parque acuático.',
    icon: '💦',
    category: 'secret',
    unlocked: false,
    secret: true,
    hint: 'Este recuerdo todavía no ha sido descubierto.',
    rewardXp: 70,
    rewardCoins: 60,
    rewardBones: 2,
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1541364983658-dd1531e21b8c?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Los espejos, las paredes y tu propia ropa quedaron salpicados de agua tibia y risas.',
  },
  {
    id: 'mem-sec-unexpected-nap',
    title: 'La siesta inesperada',
    description: 'Cayó en profundo sueño con la cabeza apoyada justo encima de tu pie izquierdo.',
    icon: '👟',
    category: 'secret',
    unlocked: false,
    secret: true,
    hint: 'Este recuerdo todavía no ha sido descubierto.',
    rewardXp: 50,
    rewardCoins: 40,
    rewardBones: 1,
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1546527868-ccb7ee7dfa6a?auto=format&fit=crop&w=600&q=80',
    eventStory: 'No te atreviste a moverte en media hora para no despertar esa ternura.',
  },
  {
    id: 'mem-sec-lost-sock',
    title: 'El calcetín perdido',
    description: 'Enterró un calcetín entre las sábanas para asegurarse de tenerlo cerca.',
    icon: '🧺',
    category: 'secret',
    unlocked: false,
    secret: true,
    hint: 'Este recuerdo todavía no ha sido descubierto.',
    rewardXp: 60,
    rewardCoins: 45,
    rewardBones: 2,
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1601758228041-f3b2795255f1?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Lo escondió tan bien que casi se le olvida a él mismo dónde estaba.',
  },
  {
    id: 'mem-sec-big-race',
    title: 'La gran carrera',
    description: 'Los famosos "zoomies": tres vueltas a la sala a toda velocidad sin frenos.',
    icon: '💨',
    category: 'secret',
    unlocked: false,
    secret: true,
    hint: 'Este recuerdo todavía no ha sido descubierto.',
    rewardXp: 65,
    rewardCoins: 50,
    rewardBones: 2,
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Derrapó en la esquina de la alfombra con una sonrisa que le iba de oreja a oreja.',
  },
  {
    id: 'mem-sec-perfect-day',
    title: 'El día perfecto',
    description: 'Comió, jugó, tomó su baño, recibió mimos y durmió feliz: ¡un 10 de 10!',
    icon: '🌟',
    category: 'secret',
    unlocked: false,
    secret: true,
    hint: 'Este recuerdo todavía no ha sido descubierto.',
    rewardXp: 120,
    rewardCoins: 150,
    rewardBones: 4,
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Al final del día suspiró feliz, sabiendo que vive en el mejor hogar del planeta.',
  },
  {
    id: 'mem-sec-perfect-nap',
    title: 'La siesta perfecta',
    description: 'Durmió con la panza llena de golosinas después de una sesión épica de pelota.',
    icon: '🌙',
    category: 'secret',
    unlocked: false,
    secret: true,
    hint: 'Este recuerdo todavía no ha sido descubierto.',
    rewardXp: 75,
    rewardCoins: 70,
    rewardBones: 2,
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1541599540903-216a46ca1dc0?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Ronquiditos suaves llenaron la habitación en una tarde tranquila.',
  },
  {
    id: 'mem-sec-master-thief',
    title: 'El gran ladrón',
    description: 'Calcetines, chancletas y toallas: nadie escapa de su patrullaje recolector.',
    icon: '🕶️',
    category: 'secret',
    unlocked: false,
    secret: true,
    hint: 'Este recuerdo todavía no ha sido descubierto.',
    rewardXp: 100,
    rewardCoins: 120,
    rewardBones: 3,
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Creó un pequeño museo de objetos prestados bajo su almohada.',
  },
  {
    id: 'mem-sec-best-friend',
    title: 'Mejor amigo',
    description: 'Cuando tienes un día largo, Golden apoya su mentón en tu rodilla y todo mejora.',
    icon: '💖',
    category: 'secret',
    unlocked: false,
    secret: true,
    hint: 'Este recuerdo todavía no ha sido descubierto.',
    rewardXp: 150,
    rewardCoins: 200,
    rewardBones: 5,
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1535930891776-0c2dfb7fda1a?auto=format&fit=crop&w=600&q=80',
    eventStory: 'No hacen falta palabras entre ustedes dos: un ladrido suave lo dice todo.',
  },
  {
    id: 'mem-sec-fresh-golden',
    title: 'Fresh Golden',
    description: 'El cachorro más fresco, perfumado y con la bandana más elegante de la ciudad.',
    icon: '🧼',
    category: 'secret',
    unlocked: false,
    secret: true,
    hint: 'Este recuerdo todavía no ha sido descubierto.',
    rewardXp: 80,
    rewardCoins: 90,
    rewardBones: 2,
    rewardAccessoryId: 'bandana-fresh',
    defaultPhotoUrl: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=600&q=80',
    eventStory: 'Moviendo las orejitas esponjadas como modelo de pasarela canina.',
  },
];

// --- TRAVESURAS INTERACTIVAS Y TRAVESURA DEL DÍA ---
export const MISCHIEF_PRESETS: MischiefItem[] = [
  {
    id: 'mischief-sock',
    title: 'El calcetín veloz',
    category: 'objects',
    description: 'Golden encuentra un calcetín abandonado, lo huele con curiosidad, lo toma firmemente y sale corriendo con una mirada pícara.',
    icon: '🧦',
    dialogue: '¡Mira lo que encontré! ¡Si lo quieres vas a tener que atraparme primero!',
    choiceA: {
      label: 'Intentar quitárselo',
      text: '¡Te lanzas suavemente a recuperarlo! Golden da una finta divertida y te lo devuelve batiendo la cola.',
      rewardXp: 25,
      rewardCoins: 30,
    },
    choiceB: {
      label: 'Dejarlo jugar un ratito',
      text: 'Golden sacude el calcetín triunfante, lo lanza al aire y luego se echa a masticarlo feliz a tu lado.',
      rewardXp: 20,
      rewardCoins: 25,
    },
    associatedMemoryId: 'mem-sock-stolen',
  },
  {
    id: 'mischief-slipper',
    title: 'La chancleta saltarina',
    category: 'house',
    description: 'Golden encuentra una chancleta, la toma con la boca, corre, se detiene, te mira fijamente y sale disparado otra vez.',
    icon: '🩴',
    dialogue: '¡Esta chancla tiene una textura aerodinámica perfecta! ¿A que no me alcanzas?',
    choiceA: {
      label: 'Atrapar a Golden',
      text: '¡Lo alcanzas y le haces cosquillas en el lomo! Golden suelta la chancleta y te da un lengüetazo.',
      rewardXp: 25,
      rewardCoins: 30,
    },
    choiceB: {
      label: 'Cambiar por un juguete',
      text: 'Le ofreces su pelota y Golden hace el canje encantado: ¡gana-gana para todos!',
      rewardXp: 30,
      rewardCoins: 20,
    },
    associatedMemoryId: 'mem-slipper-stolen',
  },
  {
    id: 'mischief-food',
    title: 'El robo de comida',
    category: 'food',
    description: 'Golden detecta un aroma irresistible en la mesa. Te mira a ti, mira el plato, vuelve a mirarte y se acerca con pasos sigilosos...',
    icon: '🍗',
    dialogue: 'Ese pedacito de pollo me está llamando por mi nombre... juro que lo escuché.',
    choiceA: {
      label: 'Detenerlo a tiempo',
      text: 'Dices con voz firme: "¡No señor!". Golden se detiene, baja las orejas y pone una cómica cara de puchero.',
      rewardXp: 30,
      rewardCoins: 25,
    },
    choiceB: {
      label: 'Darle una golosina canina',
      text: 'Lo distraes con una galleta apta para perros. Golden se relame con cara de inocente premiado.',
      rewardXp: 35,
      rewardCoins: 35,
    },
    associatedMemoryId: 'mem-food-stolen',
  },
  {
    id: 'mischief-towel',
    title: 'La toalla fugitiva',
    category: 'bath',
    description: 'Golden agarra la toalla del baño y corretea con ella como si fuera una capa de superhéroe.',
    icon: '🦸‍♂️',
    dialogue: '¡Soy Super-Golden! ¡El protector de las galletas!',
    choiceA: {
      label: 'Aplaudir su heroísmo',
      text: 'Golden da una vuelta olímpica y se sienta orgulloso con su capa.',
      rewardXp: 25,
      rewardCoins: 20,
    },
    choiceB: {
      label: 'Envolverlo en un abrazo',
      text: 'Lo arropas como un burrito perruno. ¡Se queda inmóvil y calentito ronroneando!',
      rewardXp: 30,
      rewardCoins: 25,
    },
    associatedMemoryId: 'mem-sec-who-left-that',
  },
  {
    id: 'mischief-cushion',
    title: 'El montículo del cojín',
    category: 'house',
    description: 'Golden arrastró los cojines para armar un nido perfecto en el centro de la sala.',
    icon: '🛋️',
    dialogue: 'Rediseñé la arquitectura de la sala. De nada.',
    choiceA: {
      label: 'Acomodarse a su lado',
      text: 'Te sientas con él en el nuevo nido y se acurruca en tu regazo.',
      rewardXp: 25,
      rewardCoins: 25,
    },
    choiceB: {
      label: 'Festejar su obra maestra',
      text: 'Golden mueve la cola orgulloso como el mejor decorador de interiores.',
      rewardXp: 20,
      rewardCoins: 20,
    },
  },
];

// --- EVENTOS ESPONTÁNEOS ---
export const SPONTANEOUS_EVENT_PRESETS: SpontaneousEvent[] = [
  {
    id: 'event-what-found',
    title: '¿Qué encontraste?',
    type: 'what_did_you_find',
    icon: '🎁',
    description: 'Golden aparece caminando con un objeto misterioso entre sus patas, mirándote fijamente.',
    dialogue: '¡Encontré algo increíble escondido! ¿Quieres ver qué es?',
    choiceA: {
      label: 'Investigar',
      reaction: 'Golden abre la boca y deja caer una pelota brillante que creías perdida. ¡Qué tesoro!',
      rewardXp: 30,
      rewardCoins: 35,
      effectStats: { fun: 15, love: 10 },
    },
    choiceB: {
      label: 'Festejarlo con una caricia',
      reaction: 'Golden salta de alegría batiendo la cola y te entrega su hallazgo.',
      rewardXp: 25,
      rewardCoins: 25,
      effectStats: { love: 20 },
    },
    associatedMemoryId: 'mem-first-surprise',
  },
  {
    id: 'event-hungry-eyes',
    title: 'Creo que tiene hambre...',
    type: 'hungry_eyes',
    icon: '🥺',
    description: 'Golden te mira fijamente con ojos redondos y tiernos. Luego mira su plato vacío, y vuelve a mirarte inclinando la cabeza.',
    dialogue: 'Mi pancita dice que es hora de un aperitivo... ¿no escuchas su rugidito?',
    choiceA: {
      label: 'Servirle un bocadito',
      reaction: '¡Sus ojitos brillan de emoción! Devora su premio en un segundo y te da las gracias con una pata.',
      rewardXp: 20,
      rewardCoins: 15,
      effectStats: { hunger: 20, love: 15 },
    },
    choiceB: {
      label: 'Darle un abrazo cariñoso',
      reaction: 'Se acurruca contra ti, aunque sin perder de vista la dirección de la cocina.',
      rewardXp: 25,
      rewardCoins: 10,
      effectStats: { love: 25 },
    },
  },
  {
    id: 'event-where-was-it',
    title: '¿Dónde estaba?',
    type: 'where_was_it',
    icon: '🔍',
    description: 'Golden asoma la cabeza lentamente desde abajo de la mesa. Lleva un calcetín en la boca con cara de total sigilo.',
    dialogue: 'Shhh... si no me muevo, nadie me ve. Soy una sombra dorada.',
    choiceA: {
      label: 'Hacerle "¡Buuu!" amistosamente',
      reaction: '¡Pega un brinco de sorpresa y suelta el calcetín meneando la cola a toda velocidad!',
      rewardXp: 25,
      rewardCoins: 25,
      effectStats: { fun: 25 },
    },
    choiceB: {
      label: 'Pedírselo con la mano extendida',
      reaction: 'Camina despacito y deposita el calcetín con ternura en tu palma.',
      rewardXp: 30,
      rewardCoins: 20,
      effectStats: { love: 15, fun: 15 },
    },
  },
  {
    id: 'event-zoomies',
    title: '¡Hora de los zoomies!',
    type: 'zoomies',
    icon: '⚡',
    description: 'Una chispa de energía pura invade a Golden: ¡empieza a correr en círculos como un bólido por toda la habitación!',
    dialogue: '¡¡NO PUEDO PARAR!! ¡¡MIS PATITAS TIENEN TURBO ACTIVADO!!',
    choiceA: {
      label: 'Animarlo tocando palmas',
      reaction: '¡Aumenta la velocidad haciendo piruetas y derrapes cómicos en la alfombra!',
      rewardXp: 35,
      rewardCoins: 30,
      effectStats: { fun: 35, energy: -15 },
    },
    choiceB: {
      label: 'Esperar a que se calme riendo',
      reaction: 'Termina su maratón y se desploma exhausto con la lengua afuera y sonrisa feliz.',
      rewardXp: 25,
      rewardCoins: 20,
      effectStats: { fun: 20, happiness: 15 },
    },
    associatedMemoryId: 'mem-sec-big-race',
  },
  {
    id: 'event-after-bath',
    title: 'Después del baño',
    type: 'after_bath',
    icon: '💦',
    description: 'Recién bañado, Golden planta bien las patas y se prepara para la legendaria sacudida con zoomies.',
    dialogue: '¡Cuidado los que estén cerca! ¡Va la tormenta de gotas!',
    choiceA: {
      label: 'Cubrirse a tiempo',
      reaction: '¡Te cubres justo cuando salpica en 360 grados! Quedó esponjoso como una nube.',
      rewardXp: 30,
      rewardCoins: 25,
      effectStats: { cleanliness: 15, fun: 20 },
    },
    choiceB: {
      label: 'Secarlo con una toalla tibia',
      reaction: 'Le frotas el lomo y cierra los ojos disfrutando el calorcito.',
      rewardXp: 35,
      rewardCoins: 30,
      effectStats: { cleanliness: 20, love: 20 },
    },
    associatedMemoryId: 'mem-sec-bath-disaster',
  },
  {
    id: 'event-affection-moment',
    title: 'Momento de cariño',
    type: 'affection_moment',
    icon: '🥰',
    description: 'Golden se acerca sin hacer ruido, se sienta a tu lado e inclina su cabecita apoyándola suavemente en tu mano.',
    dialogue: 'Solo quería estar cerquita tuyo... no necesito nada más.',
    choiceA: {
      label: 'Acariciarle las orejitas',
      reaction: 'Suspira hondo de felicidad y cierra los ojos en un estado de paz absoluta.',
      rewardXp: 40,
      rewardCoins: 20,
      effectStats: { love: 30, happiness: 25 },
    },
    choiceB: {
      label: 'Decirle lo buen chico que es',
      reaction: 'Mueve la puntita de la cola con timidez y te mira con adoración total.',
      rewardXp: 35,
      rewardCoins: 25,
      effectStats: { love: 25, happiness: 20 },
    },
    associatedMemoryId: 'mem-sec-best-friend',
  },
  {
    id: 'event-fell-asleep',
    title: 'Se quedó dormido',
    type: 'fell_asleep',
    icon: '💤',
    description: 'Golden se quedó dormido en la posición más extraña y graciosa, con una patita en el aire sobre una almohada.',
    dialogue: 'Zzz... persiguiendo galletas voladoras... Zzz...',
    choiceA: {
      label: 'Taparlo con su mantita',
      reaction: 'Respira aliviado y se acurruca profundamente en su sueño perruno.',
      rewardXp: 30,
      rewardCoins: 20,
      effectStats: { sleep: 25, energy: 20 },
    },
    choiceB: {
      label: 'Darle un beso suave en la cabeza',
      reaction: 'Mueve una orejita dormida y sigue soñando tranquilo.',
      rewardXp: 35,
      rewardCoins: 20,
      effectStats: { love: 25, sleep: 20 },
    },
    associatedMemoryId: 'mem-sec-unexpected-nap',
  },
];

// Helper to determine personality traits
export function calculateDominantPersonality(personality?: UserPetPersonality): string {
  if (!personality) return 'Curioso & Juguetón 🐾';
  const { playCount, affectionCount, foodInteractions, mischiefCount, bathCount } = personality;

  const maxVal = Math.max(playCount, affectionCount, foodInteractions, mischiefCount, bathCount);
  if (maxVal === 0) return 'Curioso & Juguetón 🐾';

  if (maxVal === mischiefCount && mischiefCount > 3) return 'Travieso & Aventurero 🧦';
  if (maxVal === affectionCount) return 'Cariñoso & Protector ❤️';
  if (maxVal === playCount) return 'Atlético & Energético ⚡';
  if (maxVal === foodInteractions) return 'Glotón & Simpático 🍖';
  if (maxVal === bathCount) return 'Limpio & Elegante ✨';

  return 'Noble & Fiel 🌟';
}
